# Change these first
owner: eruci # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: 3geonames
    url: https://3geonames.org
  - name: geocode.xyz
    url: https://geocode.xyz
  - name: geocoder.ca
    url: https://geocoder.ca
  - name: Foodpages.ca
    url: https://foodpages.ca
  - name: dinehere.us
    url: https://dinehere.us

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.3geonames.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://geocode.xyz/geocodelogo.svg
  name: Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
